# -*- coding: utf-8 -*-
"""Ak Chatbot

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eYD9O815cmWSpfCwTjhiWGMxIZLIpbD1
"""

#Data Loading first step
from langchain_community.document_loaders import TextLoader
loader = TextLoader('sustainable 3.docx',encoding="utf-8")
loader

!pip install docx2txt
from langchain_community.document_loaders import Docx2txtLoader

# Re-initialize the loader with the correct type for .docx files
loader = Docx2txtLoader('sustainable 3.docx')

text_documents = loader.load()
text_documents

# Text splitting
from langchain_text_splitters import RecursiveCharacterTextSplitter
text_splitter = RecursiveCharacterTextSplitter(chunk_size=200, chunk_overlap=20)
finalDocuments = text_splitter.split_documents(text_documents)
finalDocuments

# If finalDocuments is a list of Documents objects:
text = [doc.page_content for doc in finalDocuments]

#HuggingFace embedding
import os
from dotenv import load_dotenv
load_dotenv()

os.environ['HF_TOKEN'] = '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'

!pip install langchain-huggingface
from langchain_huggingface import HuggingFaceEmbeddings
embeddings = HuggingFaceEmbeddings(model_name="sentence-transformers/all-MiniLM-L6-v2")

print(embeddings)

!pip install faiss-cpu
from langchain_community.vectorstores import FAISS
db = FAISS.from_documents(finalDocuments, embeddings)
db

query = input("Enter your question?: ")
docs = db.similarity_search(query)

for doc in docs:
    print(doc.page_content)

